# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: yes

r:
 - release

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr);codecov()'
 
notifications:
  email:
    recipients:
      - srikkanth18@gmail.com
    on_success: change
    on_failure: always
