# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: yes

r:
 - release

r_github_packages:
  - jimhester/covr
  
install:
  - npm install
  
script:
  - npm run build

after_success:
  - Rscript -e 'library(covr);codecov()'
  - Rscript -e 'covr::coveralls()'
 
notifications:
  email:
    recipients:
      - srikkanth18@gmail.com
    on_success: change
    on_failure: always
